### ISSUE TITLE
Push to jCenter

### ISSUE THREAD

**Issue by ticofab** [oschrenk/sunrise.scala#1]
Thanks for your work @oschrenk ! Could you publish this to jCenter? (Bintray can do it automatically and for free)

**Comment by oschrenk** [comment]
See https://jcenter.bintray.com/com/oschrenk/sunrise-scala_2.12/0.1.0/

If you need 2.11, let me know

**Comment by ticofab** [comment]
👍 - no need for 2.11 :)
