### ISSUE TITLE
Richer return type for SunriseSunset.of

### ISSUE THREAD

**Issue by ticofab** [oschrenk/sunrise.scala#3]
hey Oliver,
holidays means time to look into stuff, so here's the example I was thinking about, using a common sealed trait:

```scala
sealed trait SunriseSunset

case object PolarDay extends SunriseSunset

case object PolarNight extends SunriseSunset

case class SunriseSunsetTimes(sunriseTime: Long, sunsetTime: Long) extends SunriseSunset

object SunriseSunset {
  def of(lat: Long, lon: Long, zone: ZoneId): SunriseSunset = {
    // here, your custom logic, and return one of the things above, for example
    // PolarDay
    // PolarNight
    SunriseSunsetTimes(8, 22)
  }
}

// then later in the client app,
SunriseSunset.of(myLatitude, myLongitude, "Europe/Amsterdam") match {
  case PolarDay => println("polar day!")
  case PolarNight => println("polar night!")
  case SunriseSunsetTimes(morning, night) => println(morning + " " + night)
}
```

This is it. Of course all Ints should be proper types :)

**Comment by oschrenk** [comment]
Makes sense. 

See https://github.com/oschrenk/sunrise.scala/pull/4/files

Instead of `SunriseSunsetTimes` I used `Day`

**Comment by ticofab** [comment]
Nice! I'm not sure why to include the LocalDate in the Polar objects, but great work :)

**Comment by ticofab** [comment]
Is this going to make it to jCenter? :)

**Comment by oschrenk** [comment]
Good point about the `LocalDate`. Removed it.

I'm actually thinking a lot about the date information and especially the timezone information. I will probably remove it, so that one only gets the GMT time back. It's up to the developer to figure out the time zone of the location.

**Comment by oschrenk** [comment]
Release 0.5.1
